name = "analyzer-backend"
compatibility_date = "2023-10-12"
type = "webpack"
account_id = "5ad2ddf9aa06683d90aa5df60149f527"
workers_dev = true
route = ""
zone_id = ""

[build]
entry_point = "backend/analyzer-backend/bundled-worker.js"
